export const positionData = [ "Point Guard", "Shooting Guard", "Small Forward", "Power Forward", "Center"]

export const playerData = [
  {
    name: "Deandre Ayton",
    team: "Phoenix Suns",
    logo: "https://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/PHX.svg",
    pick: "1st overall",
    position: "Center",
    school: "Arizona (Fr.)",
    video: "https://www.youtube.com/watch?v=B6IlKe_k_ac",
    comparison: "David Robinson",
    stats: "20.1 PPG, 11.6 RPG, 1.9 BPG",
    description: "Ayton figures to be a productive NBA player, the kind of big man who can generate 20 points and 10 rebounds with regularity, but the concerns about how he fits the modern game are tough to sweep under the rug. The 19-year-old likely needs to be one of the five best offensive centers in the league to provide positive value in terms of his contributions to winning. That's a tough benchmark.",
    background: "#1D1160",
    traded: ""
  },
  {
    name: "Marvin Bagley III",
    team: "Sacramento Kings",
    logo: "https://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/SAC.svg",
    pick: "2nd overall",
    position: "Power Forward",
    school: "Duke (Fr.)",
    video: "https://www.youtube.com/watch?v=2A7ceXNRMsk",
    comparison: "Amare Stoudemire",
    stats: "21.2 PPG, 11.3 RPG, 61.4% FG",
    description: "It wouldn't be an NBA Draft without the Kings using their top-10 pick to select a center. Sacramento lands the No. 3-ranked prospect on our board, hoping to pair him with Harry Giles for the frontcourt of the future. Bagley should be a productive player in the NBA. His elite athleticism and rim running will translate quickly. He still needs to develop defensively if he's going to provide positive value overall.",
    background: "red",
    traded: ""
  },
  {
    name: "Luka Dončić",
    team: "Dallas Mavericks",
    logo: "https://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/DAL.svg",
    pick: "3rd overall",
    position: "Shooting Guard",
    school: "Real Madrid (Spain)",
    video: "https://www.youtube.com/watch?v=fwSRpOq6Psg",
    comparison: "Ben Simmons",
    stats: "14.1 PPG, 5.2 RPG, 4.5 APG",
    description: "The 6-8 wing is an outstanding pick-and-roll ball-handler, the best passer in the draft and a projectable shooter. The big question is how he fits alongside 2017 first-round pick Dennis Smith Jr. Doncic's success for the Slovenian national team during the EuroBasket tournament when he played next to Goran Dragic can provide a blueprint. Doncic could have gone No. 1 - he's terrific value here.",
    background: "red",
    traded: "(Traded from Atlanta Hawks)"
  },
  {
    name: "Jaren Jackson Jr.",
    team: "Memphis Grizzlies",
    logo: "https://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/MEM.svg",
    pick: "4th overall",
    position: "Power Forward",
    school: "Michigan State (Fr.)",
    video: "https://www.youtube.com/watch?v=75PDZZL0_Fw",
    comparison: "Serge Ibaka",
    stats: "10.9 PPG, 5.8 RPG, 3.0 BPG",
    description: "Jackson's high number of fouls and lack of points per game production has underrated his long-term potential. The 6-11 center is the best defensive prospect in the class. He can protect the rim and switch onto just about anybody. His offensive game already includes a 3-point shot that's functional out of pick-and-pops, and he has flashed impressive potential off the bounce attacking closeouts.",
    background: "red",
    traded: ""
  },
  {
    name: "Trae Young",
    team: "Atlanta Hawks",
    logo: "https://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/ATL.svg",
    pick: "5th overall",
    position: "Point Guard",
    school: "Oklahoma (Fr.)",
    video: "https://www.youtube.com/watch?v=fwSRpOq6Psg",
    comparison: "Mike Bibby",
    stats: "27.4 PPG, 8.8 APG, 36.1% 3FG",
    description: "Young is no Stephen Curry - that's an unfair comparison both for the prospect and the future Hall of Famer - but he has the potential to be a dangerous pull-up threat with deep 3-point range and the court vision to punish rotating defenders. Young faces significant defensive concerns, but his potential to make a team's offense better is too much to pass up given the importance of primary initiators in the modern game.",
    background: "red",
    traded: "(Traded from Dallas Mavericks)"
  },
  {
    name: "Mohammed Bamba",
    team: "Orlando Magic",
    logo: "https://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/ORL.svg",
    pick: "6th overall",
    position: "Center",
    school: "Texas (Fr.)",
    video: "https://www.youtube.com/watch?v=ryIkng6ExXQ",
    comparison: "Rudy Gobert",
    stats: "12.9 PPG, 10.5 RPG, 3.7 BPG",
    description: "The 7-footer fits the profile of what the Magic's front office is looking for in terms of positional size. Bamba still has quite a ways to go in terms of his offensive ability. Yes, he's shown off a new jump shot in workouts, but we'll need to see it translate against actual competition to be sure. In the meantime, Bamba should provide Orlando with a defensive anchor on the backline.",
    background: "red",
    traded: ""
  },
  {
    name: "Wendell Carter",
    team: "Chicago Bulls",
    logo: "https://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/CHI.svg",
    pick: "7th overall",
    position: "Center",
    school: "Duke (Fr.)",
    video: "https://www.youtube.com/watch?v=VMddNezbqvI",
    comparison: "Al Horford",
    stats: "13.5 PPG, 9.1 RPG, 2.1 BPG",
    description: "Carter is a terrific prospect because of the versatility of his offensive game, but his defensive pairing with Lauri Markkanen will be worth keeping an eye on. The former Blue Devil's average mobility on the perimeter could limit some of the Bulls' options defending ball screens. That said, this frontcourt is optimized for basketball's future on the offensive end.",
    background: "red",
    traded: ""
  },
  {
    name: "Collin Sexton",
    team: "Cleveland Cavaliers",
    logo: "https://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/CLE.svg",
    pick: "8th overall",
    position: "Point Guard",
    school: "Alabama (Fr.)",
    video: "https://www.youtube.com/watch?v=GkXPbIT09PY",
    comparison: "Eric Bledsoe",
    stats: "19.2 PPG, 3.6 APG, 33.6% 3FG",
    description: "The Alabama point guard fits a position of need for the Cavaliers, but he struggled to create for teammates in college and didn't flash high-level basketball IQ. Sexton's competitiveness, toughness and work ethic could push him to reach his ceiling. It's just not clear that ceiling is particularly high.",
    background: "red",
    traded: "(from Brooklyn via Boston)"
  },
  {
    name: "Kevin Knox",
    team: "New York Knicks",
    logo: "https://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/NYK.svg",
    pick: "9th overall",
    position: "Small Forward",
    school: "Kentucky (Fr.)",
    video: "https://www.youtube.com/watch?v=Igs9855WQQg",
    comparison: "Tobias Harris",
    stats: "15.6 PPG, 5.4 RPG, 34.1% 3FG",
    description: "The Knicks reportedly fell in love with Knox following a workout he had in front of the team against Miles Bridges. The 6-9 forward combines youth, positional size and projectable shooting. However, his lack of production in many of the other stats raises valid questions about his ceiling. Ultimately, Knox feels like he'll end up as a complementary piece next to Kristaps Porzingis - and hopefully at least one other star in New York over the long-term.",
    background: "red",
    traded: "th overall"
  },
  {
    name: "Mikal Bridges",
    team: "Phoenix Suns",
    logo: "https://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/PHX.svg",
    pick: "10th overall",
    position: "Small Forward",
    school: "Villanova (Jr.)",
    video: "https://www.youtube.com/watch?v=6uc37rMkxh0",
    comparison: "Otto Porter",
    stats: "17.7 PPG, 5.3 RPG, 43.5% 3FG",
    description: "Bridges had to work to get where he is, but last season he broke out for 17.7 points and 5.3 assists a game while shooting 44 percent from 3-point range. He’s big enough to create his own shots, smart enough to help his team when he doesn’t have the ball, and skilled enough to match up defensively with elite guards and small forwards. He could stand to get a bit stronger, but his two-way impact could be Klay Thompson-like.",
    background: "red",
    traded: "(Traded from Philadelphia via L.A. via Phoenix)"
  }
]